server:
  port: 8080
spring:
  output:
    ansi:
      enabled: always
  datasource:
    #postgresql://postgres:49fLUHHaU1nC8Re6eYCH@containers-us-west-146.railway.app:6854/railway
    url: jdbc:postgresql://containers-us-west-146.railway.app:6854/railway
    username: postgres
    password: 49fLUHHaU1nC8Re6eYCH
  liquibase:
    change-log: classpath:db/changelog/db-changelog.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    #        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
  data:
    rest:
      base-path: "/api/v2"
      detection-strategy: annotated

springdoc:
  swagger-ui:
    path: /swagger-ui
